Сделала генерацию данных
htmlacademy-univer-javascript-1/2579467-kekstagram-5 pull request #4
Opened 2024-11-27 15:57 UTC by animuyr

2024-12-01 07:30 UTC, dimohqa requested changes

2024-12-01 07:30 UTC, dimohqa commented on js/main.js
> +  max = Math.floor(max);
Опять мутируешь аргументы функции, давай поправим

2024-12-01 07:30 UTC, dimohqa commented on js/main.js
> +}
А чем отличаются все эти функции? Можно сделать одну

2024-12-01 07:30 UTC, dimohqa commented on js/main.js
> +      message: "Всё отлично!",
В задании указано как надо сгенерировать сообщения для комментариев

> Для формирования текста комментария — message — вам необходимо взять одно или два случайных предложения из представленных ниже

2024-12-01 07:30 UTC, dimohqa commented on js/main.js
> +      comment: getCommentsArray(),
comment**s**

2024-12-01 07:30 UTC, dimohqa commented on js/main.js
> +    commentArray.push(comment);
Рекомендация, не обязательно править:
Можешь почитать про Array.from(), где вторым аргументом можно передать функцию, которая будет применяться к каждому элементу массива. Тогда не придется создавать пустой массив и цикл for

2024-12-01 10:24 UTC, animuyr commented on js/main.js
> +  max = Math.floor(max);
Исправила

2024-12-01 10:29 UTC, animuyr commented on js/main.js
> +      message: "Всё отлично!",
Исправила

2024-12-01 10:41 UTC, animuyr commented on js/main.js
> +}
Cделала

2024-12-01 11:04 UTC, animuyr commented on js/main.js
> +    commentArray.push(comment);
Почитала, поправила

2024-12-02 04:02 UTC, dimohqa commented on js/main.js
> +      message: "Всё отлично!",
> **взять одно или два случайных предложения** 

в задании имелось ввиду, что надо случайно определить сколько предложений будет в комментарии: одно или два

2024-12-02 09:14 UTC, animuyr commented on js/main.js
> +      message: "Всё отлично!",
Сделала

2024-12-03 09:26 UTC, merged